### ISSUE TITLE
Step forward

### ISSUE THREAD

**Issue by cliffordsnow** [openbrian/osm-microcosms#14]
This would be an enhancement that probably won't be needed initially. 

Create a way, like Meetup, to transfer ownership to another member of the group. Or if someone no longer wants the role but no one else is willing to step forward, to allow a member to claim the group.

**Comment by openbrian** [comment]
Moved "Create a way, like Meetup, to transfer ownership to another member of the group. " to #20.

**Comment by openbrian** [comment]
@cliffordsnow If you're satisfied, please close this ticket (or on the github project page, move this card to Done).
