### ISSUE TITLE
When click "Yes" to "Are you going?" to Event add one to the tally

### ISSUE THREAD

**Issue by RobJN** [openbrian/osm-microcosms#30]
There is no visual feedback when you click that you are attending an event and the number of people going does not increase until you refresh the page.

**Comment by openbrian** [comment]
@RobJN Ready for review.  Give it 15 minutes to test and deploy.

**Comment by openbrian** [comment]
I'm also going to hide the irrelevant button.

**Comment by RobJN** [comment]
Yes, that's fixed it. Much appreciated 👍

**Comment by openbrian** [comment]
Was fixed by fb2dd4d2aae2191d97d28b885864054361f1e254
