### ISSUE TITLE
Are you going?

### ISSUE THREAD

**Issue by mmd-osm** [openbrian/osm-microcosms#34]
I'm not logged on and heading to https://microcosms.apis.dev.openstreetmap.org/events/3 

```
1 people are going.
Are you going?
YES/NO
```

When I click on "YES", or "NO", the site redirects to https://microcosms.apis.dev.openstreetmap.org/event_attendances, and I see and empty screen. The error console shows an HTTP 403 error.

I would expect either a log on page, or no option to say YES/NO in the first place, unless I'm logged in.

I think the same issue applies when you try to join a microcosm as long as you're not logged in.

**Comment by openbrian** [comment]
I see this issue.  Working on it.

**Comment by openbrian** [comment]
Fixed with 6eeb82affd49a1c0cd44863554b1c6c1481fb8ce.
